### PR TITLE
docker trust sign: check local image cache before initializing notary repo

### LINKED ISSUE #60: docker trust sign should check if the image exists first before initializing
Ideally, we should fail fast if the image doesn't exist remotely or locally.  I think we just have to add the local check.

```
$ ./docker-darwin-amd64 trust sign riyaz/demo:new
Signing and pushing trust metadata for riyaz/demo:new
Enter passphrase for root key with ID 1908a0c:
Enter passphrase for new repository key with ID 9af97c2:
Repeat passphrase for new repository key with ID 9af97c2:
Enter passphrase for new targets/riyaz key with ID 3cfa79d:
Repeat passphrase for new targets/riyaz key with ID 3cfa79d:
Created signer: riyaz
Finished initializing "docker.io/riyaz/demo"
The push refers to a repository [docker.io/riyaz/demo]
An image does not exist locally with the tag: riyaz/demo
```

### PR DESCRIPTION
**Pull request by riyazdf**
Confirmed that this is a proper way to check if a local image exists with docker/cli folks.  We'll want a better integration test once the framework is in place.

Closes #60 

Signed-off-by: Riyaz Faizullabhoy <riyaz.faizullabhoy@docker.com>

### CODE REVIEW

File: cli/command/trust/sign.go [hunk 1]
```diff
@@ -85,6 +91,11 @@ func signImage(cli command.Cli, imageName string) error {
 	return nil
 }
 
+func checkLocalImageExistence(ctx context.Context, cli command.Cli, imageName string) error {
```
Comment (ashfall) [inline cli/command/trust/sign.go]: Should we consider moving this to `helpers.go`?

Comment (riyazdf) [reply cli/command/trust/sign.go]: :+1: done

**Review by ashfall — APPROVED** [review]
🚀
